server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
#        native:
#          search-locations:
        git: #default
          uri: https://github.com/choral7451/msa-e-commerce.git
          default-label: main
#          username: [username] private repo 사용시
#          password: [password] private repo 사용시

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - httptrace
          - busrefresh